In [1]:
import torch
import numpy as np

### Microsoft learn
https://docs.microsoft.com/en-us/learn/modules/intro-machine-learning-pytorch/3-data


In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"random tensor: \n {x_rand} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

random tensor: 
 tensor([[0.1846, 0.3433],
        [0.1239, 0.1924]]) 



In [7]:
shape=(2,3,)
rand_tensor = torch.rand(shape)
print(f"random tensor: \n {x_rand} \n")

random tensor: 
 tensor([[0.1846, 0.3433],
        [0.1239, 0.1924]]) 



In [8]:
tensor = torch.rand(3,4)
print(f"Shape: {tensor.shape}")
print(f"DataType: {tensor.dtype}")
print(f"Device: {tensor.device}")

Shape: torch.Size([3, 4])
DataType: torch.float32
Device: cpu


In [9]:
torch.cuda.is_available()

False

In [10]:
tensor = torch.ones(4,4)
tensor1 = tensor[0]
tensor2 = tensor[:,0]

In [12]:
tensor = torch.ones(4,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [13]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [14]:
y1 = tensor @ tensor.T

In [15]:
print(tensor.T)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [17]:
y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T, out=y3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [18]:
print(tensor.sum())

tensor(16.)


In [19]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
